//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoEconomato
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gestão_EconomatoEntities : DbContext
    {
        public Gestão_EconomatoEntities()
            : base("name=Gestão_EconomatoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<EncomendasCliente> EncomendasClientes { get; set; }
        public virtual DbSet<EncomendasFornecedor> EncomendasFornecedors { get; set; }
        public virtual DbSet<Fornecedor> Fornecedors { get; set; }
        public virtual DbSet<Funcionario> Funcionarios { get; set; }
        public virtual DbSet<Plafond> Plafonds { get; set; }
        public virtual DbSet<Produto> Produtoes { get; set; }
        public virtual DbSet<Produto_Fornecedor> Produto_Fornecedor { get; set; }
        public virtual DbSet<ProdutoEncomendarCliente> ProdutoEncomendarClientes { get; set; }
        public virtual DbSet<ProdutoEncomendarFornecedor> ProdutoEncomendarFornecedors { get; set; }
        public virtual DbSet<Utilizadore> Utilizadores { get; set; }
    }
}
