//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoEconomato
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plafond
    {
        public int id { get; set; }
        public System.DateTime data { get; set; }
        public int quantidade_pedida { get; set; }
        public string estado { get; set; }
        public string Id_Cliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
