//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoEconomato
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto_Fornecedor
    {
        public int id { get; set; }
        public int Id_Produto { get; set; }
        public int Id_Fornecedor { get; set; }
    
        public virtual Fornecedor Fornecedor { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
