//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoEconomato
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produto()
        {
            this.Produto_Fornecedor = new HashSet<Produto_Fornecedor>();
            this.ProdutoEncomendarClientes = new HashSet<ProdutoEncomendarCliente>();
            this.ProdutoEncomendarFornecedors = new HashSet<ProdutoEncomendarFornecedor>();
        }
    
        public int id { get; set; }
        public string Nome { get; set; }
        public string Setor { get; set; }
        public int Stock { get; set; }
        public int Preco { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produto_Fornecedor> Produto_Fornecedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutoEncomendarCliente> ProdutoEncomendarClientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutoEncomendarFornecedor> ProdutoEncomendarFornecedors { get; set; }
    }
}
